### ISSUE TITLE
Product Landing Page Challenge doesn't recognize action on form

### ISSUE THREAD

**Issue by Astolfoj** [freeCodeCamp/testable-projects-fcc#1041] opened 2020-02-04 20:38 UTC
#### Issue Description

On the product landing page challenge for html and css section of the course there's a bug that causes it to not really that an action has been asigned to the #form id. It appears to be looking for a "name" attribute in the input tag with "email" id, so unless one reads the error log and adds a name="email" attribute to the input tag it'll never work.

#### Browser Information

- Browser Name, Version: Chrome, 79.0.3945.130
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/astolfor/pen/NWPVwvJ


```

#### Screenshot

![The bug in question. Not recognizing the action in the form](https://user-images.githubusercontent.com/43593037/73784386-5dd81c80-4763-11ea-85a3-7714ed7a7be0.png)
![After adding the name attribute the issue disapears](https://user-images.githubusercontent.com/43593037/73784574-bad3d280-4763-11ea-9d79-528ded143a67.png)

**Comment by RandellDawson** [comment] 2020-02-04 21:15
@Astolfoj This is not a bug.  The error message shown is valid.  In order for a form's data to be processed on a server, there must be a name attribute and corresponding value assigned to it.

**Closed by RandellDawson** 2020-02-04 21:15 UTC

**Comment by Astolfoj** [comment] 2020-02-04 21:21
I wasn't aware of that. That should probably be added to the form tutorial, since it isn't mentioned anywhere.
