### ISSUE TITLE
Tribute Project test error #7

### ISSUE THREAD

**Issue by RBLutsky** [freeCodeCamp/testable-projects-fcc#482] opened 2018-07-24 20:59 UTC
#### Issue Description

When I test my project, I get the following error/ fail: 

7. I should see an <a> element with a corresponding id="tribute-link", which links to an outside site that contains additional information about the subject of the tribute page. HINT: You must give your element an attribute of target and set it to "_blank" in order for your link to open in a new tab (i.e. target="_blank").

I believe that I have met this requirement.

#### Browser Information
* Browser Name, Version: Chrome, 67.0.3396.99
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```Pen Link: https://codepen.io/rblutsky/pen/PBWGbj

Code portion: 
<footer  role="contentinfo ">
            <a  href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets" target="_blank " "id="tribute-link">Click here to see more information</a>  
            <cite>Citation: “Cascading Style Sheets.” Wikipedia, Wikimedia Foundation, 21 July 2018, en.wikipedia.org/wiki/Cascading_Style_Sheets.</cite>     
            <p>&copy; &nbsp; 2018 Rhys Lutsky</p>
         </footer>
 
 
 
```

**Comment by tchaffee** [comment] 2018-07-25 20:22
@RBLutsky Thank you for reporting this. Is there any chance you could give us a link to your CodePen so we can reproduce the error and investigate? Thanks.

**Comment by tbushman** [comment] 2018-07-26 18:51
@RBLutsky One thing I'm noticing is some quote syntax that may be problemmatic.   
```  
... target="_blank " "id="tribute-link"  
```  
should be  
```  
target="_blank " id="tribute-link"  
```  
for example.  
Also not sure if curly quotes in raw innerHTML is a problem: `“Cascading Style Sheets.”`

**Comment by RBLutsky** [comment] 2018-08-09 16:13
Hi all,
Thanks for your help.  I tried fixing the spacing that tbushman recommended, with no change.  
Here is the link: [](url)https://codepen.io/rblutsky/pen/PBWGbj

**Comment by tbushman** [comment] 2018-08-11 01:08
@RBLutsky It appears you've fixed it, however. If you want, let us know what was wrong. Thanks.

**Comment by tchaffee** [comment] 2018-08-14 23:56
@RBLutsky Closing since you've fixed the problem. But you should still be able to leave comments, so please do let us know how you fixed it.

**Closed by tchaffee** 2018-08-14 23:56 UTC

**Comment by RBLutsky** [comment] 2018-08-20 20:54
Hi all,  Boy do I feel stupid....I had an extra quotation mark.  Once I deleted it, I was fine.  Live and learn :)@tchaffee
