### ISSUE TITLE
Cannot equal the height of the viewport

### ISSUE THREAD

**Issue by mgpandatickles** [freeCodeCamp/testable-projects-fcc#1113] opened 2020-05-01 10:21 UTC
#### Issue Description

I am trying to pass "Build a Personal Portfolio Webpage." No matter what I do, I cannot clear " The height of the welcome section should be equal to the height of the viewport" requirement. Setting height of welcome section to 100vh doesn't work... and I've also tried other ways to work around it. I am not sure this is a bug, but I don't have any better ideas.

#### Browser Information

- Browser Name, Version: Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Notebook laptop

#### Your Code / Link to Your Pen

```https://codepen.io/thriving_turtle/pen/YzyxOOx


This is the error info that I get: 
The height of #welcome-section is not equal to the height of the viewport : expected 570 to be close to 530 +/- 0
AssertionError: The height of #welcome-section is not equal to the height of the viewport : expected 570 to be close to 530 +/- 0
    at Proxy.x (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:12413)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.approximately (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:8045)
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:130276)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36606
    at i.p.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:36901)
    at N.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42814)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:43780
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42090)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42160
```

**Comment by mgpandatickles** [comment] 2020-05-01 10:23
Not sure if link to my pen showed up:
https://codepen.io/thriving_turtle/pen/YzyxOOx

**Comment by Sky020** [comment] 2020-05-01 10:56
Hello there.

In general, I would encourage you to post a topic like this on the [forum](https://www.freecodecamp.org), as the issue is not to do with the test suite, but your code.

In your example, it is the padding included in your `#welcome-section`. If you add:
```css
padding: 0;
```
You will pass the tests. Also, use the built-in analyser tool in CodePen to find some syntax errors.

I am closing this issue.

**Closed by Sky020** 2020-05-01 10:56 UTC
