### ISSUE TITLE
[Random Quote Machine] Random timeout of tests 7, 8 & 9

### ISSUE THREAD

**Issue by christophherr** [freeCodeCamp/testable-projects-fcc#26] opened 2017-01-29 20:59 UTC
#### Issue Description
Tests are failing randomly with the message:
Error: timeout of 4000ms exceeded. Ensure the done() callback is being called in this test.

```
8. When the #new-quote button is clicked, my quote machine should fetch a new quote and display it in the #text element.
Error: timeout of 4000ms exceeded. Ensure the done() callback is being called in this test.
at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7724)
at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8538
at https://rawgit.com/no-stack-dub-sack/testable-projects-fcc/master/build/bundle.js:40238:26

9. My quote machine should fetch the new quote's author when the #new-quote button is clicked and display it in the #author element.
Error: timeout of 4000ms exceeded. Ensure the done() callback is being called in this test.
at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7724)
at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8538
at https://rawgit.com/no-stack-dub-sack/testable-projects-fcc/master/build/bundle.js:40252:26
```

Just before submitting the issue, I ran the tests again and test 7 failed (see screenshot):
```
7. On first load, my quote machine displays the random quote's author in the element with id="author". ‣
Error: timeout of 4000ms exceeded. Ensure the done() callback is being called in this test.
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7724)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7934this.timeout(requestTimeout + 1000);
                return new Promise(function (resolve, reject) {
                    setTimeout(function (_) {
                        var author = document.getElementById("author");
                        if (author.innerText.length > 0) resolve();else reject("There is no initial author displayed ");
                    }, requestTimeout);
                });
```

#### Browser Information

* Browser Name, Version: Chrome, 55.0.2883.87 m (64-bit)
* Operating System: Win10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

http://codepen.io/c-herr/pen/dNWjby

#### Screenshot

http://prntscr.com/e1yfjr

**Comment by no-stack-dub-sack** [comment] 2017-02-20 18:41
@christophherr You still getting this same issue? We can try just increasing the timeout length

**Comment by christophherr** [comment] 2017-02-21 00:08
@no-stack-dub-sack 
I ran the tests several times during the last few hours and they took between 3001ms and 3005ms.
I might have just hit slow connections before.

**Comment by no-stack-dub-sack** [comment] 2017-02-25 22:55
@christophherr interesting... well, we'll leave this open for now in case it gets reproduced later by you or someone else

**Comment by tchaffee** [comment] 2017-06-20 16:39
@QuincyLarson I tested this using the CodePen posted by @christophherr and all the tests pass. I am closing this since it looks like it was a one time problem related to slow network.

**Closed by tchaffee** 2017-06-20 16:39 UTC

**Comment by roneilboodie** [comment] 2020-03-17 21:17
I am using the latest version of Mozilla Firefox, and it keep timing out, 15000ms...the exact statement is: 
"Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. "
