### ISSUE TITLE
Technical Documentation Page Test

### ISSUE THREAD

**Issue by laniehei** [freeCodeCamp/testable-projects-fcc#372] opened 2018-06-15 21:29 UTC
#### Issue Description
#Layout 1. Test does not pass, despite it working. Others have documented this issue on the message boards from minimum 1 year ago. 

#### Browser Information
* Browser Name, Version: Chrome
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/CapsLachs/pen/JZyjLP?editors=1100

On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user.

AssertionError: Please run this test in a larger window (before any media queries) : expected 789 to be above 850
    at Function.assert.isAbove (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:17717:36)
    at n.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:22132:23)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
```
 
 
 
```

**Comment by tbushman** [comment] 2018-06-17 04:46
@laniehei I was not able to reproduce this issue. Your tests pass in Chrome and Firefox. Please reopen this issue if you are still getting this error. Thank you!

**Comment by laniehei** [comment] 2018-06-17 05:38
@tbushman I rechecked this just now. I am running Chrome Version 67.0.3396.87 (Official Build) (64-bit), and my tests are showing 15/16 passing with the instance noted above not passing, even when no media queries affecting the left sidebar are in place.

**Comment by tbushman** [comment] 2018-06-17 05:56
OK sorry. I can't reproduce the issue, so I'll let someone else try.

**Comment by tbushman** [comment] 2018-07-14 01:34
Also #433

**Comment by KDCinfo** [comment] 2018-08-13 00:47
Got mine passed (after a few dozen tries) by widening the main CodePen viewing window before running the test. I'm thinking the viewable testing window needs to be at least 850px wide; then run, and test.

**Comment by tbushman** [comment] 2018-09-20 15:10
@KDCinfo Indeed. Closing.

**Closed by tbushman** 2018-09-20 15:10 UTC
Labels: help wanted
