### ISSUE TITLE
Tribute Page responsive image

### ISSUE THREAD

**Issue by gpr90662b** [freeCodeCamp/testable-projects-fcc#1137] opened 2020-05-21 19:30 UTC
#### Issue Description

I am running the test for tribute page  and test fails for responsive image test even though the image is responsive as far as I can tell.

#### Browser Information

I am using the fork on codepen from freecodecamp.org Responsive Web Design Projects - Build a Tribute Page 
- Browser Name, Version: Chrome latest version
- Operating System: Windows 10
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Responsive Web Design Projects - Build a Tribute Page</title>
    <style>
    #main {
    padding:0 20px;
    margin: 0 auto;
    }
    #title {
    font-size: 28px;
    }
    #img-div {
      text-align: center;
    }
    #image {
      max-width: 100%;
      height: auto;
    }
    
    #img-caption {
       text-align: center;
    }
    
    #tribute-info {
      font-family: san-serif;
      line-height: 1.25em;
    }
    
    #tribute-link {
      color: #442288;
    }
    </style>
    
  </head>
  <body>
   <div id="main"> 
         <h1 id="title">Dr. Norman Borlaug</h1>
         <div id="img-div">          
            <img src="https://i.imgur.com/Zju8VFI.jpg" alt="Dr. Norman Borlaug picture" id="image" width="1600" height="1315"/>
            <figcaption id= "img-caption">Dr. Norman Borlaug examining wheat crop</figcaption>
         </div>
            <p id="tribute-info">America has three living winners of the Nobel Peace Prize, two universally renowned and the other so little celebrated that not one person in a hundred would be likely to pick his face out of a police lineup, or even recognize his name. The universally known recipients are Elie Wiesel, who for leading an exemplary life has been justly rewarded with honor and acclaim, and Henry Kissinger, who in the aftermath of his Nobel has realized wealth and prestige. America's third peace-prize winner, in contrast, has been the subject of little public notice, and has passed up every opportunity to parley his award into riches or personal distinction. And the third winner's accomplishments, unlike Kissinger's, are morally unambiguous. Though barely known in the country of his birth, elsewhere in the world Norman Borlaug is widely considered to be among the leading Americans of our age.</p>
            <a id="tribute-link" href="https://en.wikipedia.org/wiki/Norman_Borlaug" target="_blank">Wikipedia page on Norman Borlaug</a>
         </div>
   </div>
  </body>
</html>



```

**Comment by Sky020** [comment] 2020-05-21 19:52
Hello there,

Please note: If you are running the tests in your own local environment, the tests will not detect much of the CSS. If you are developing the project locally, I recommend you migrate to something like CodePen, as you are expected to submit the project anyway, and it will need to be publicly hosted.

Otherwise, if this is not the case, it would be helpful if you posted a link to your project.

**Comment by gpr90662b** [comment] 2020-05-21 23:35
Well here is my codepen link:

https://codepen.io/gpr90662b/pen/gOaqeOz

**Comment by Sky020** [comment] 2020-05-22 09:46
@gpr90662b , did you read the error message?
>Use the "display" style property with a value of "block" for responsive images.: expected 'inline' to equal 'block'

The error messages are often very informative as to what the problem is.

I am closing this issue, as it is not a problem with the source code, nor the test suite. If you have any more queries, I recommend you open a topic on the [forum](https://www.freecodecamp.org/forum)

Thank you.

**Closed by Sky020** 2020-05-22 09:46 UTC

**Comment by gpr90662b** [comment] 2020-05-22 16:59
Thanks for you response, I was able to fix it!
