### ISSUE TITLE
Able to pass all tests without adding keypress event.

### ISSUE THREAD

**Issue by vardan1992** [freeCodeCamp/testable-projects-fcc#593] opened 2018-09-07 18:44 UTC
#### Issue Description

Able to pass all tests without adding keypress input.

#### Browser Information

* Browser Name, Version: chrome
* Operating System: windows 10
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/vardangupta/pen/gdmBeY
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/15278328/45237328-f9115c00-b2fb-11e8-8123-db968025c55f.png)

**Comment by ValeraS** [comment] 2018-09-07 19:27
@vardan1992 thanks for reporting this. The issue is resolved already, but a new bundle is not deployed yet.

**Comment by tbushman** [comment] 2018-09-13 08:16
Fixed in https://github.com/freeCodeCamp/cdn/pull/10

**Closed by tbushman** 2018-09-13 08:16 UTC
