### ISSUE TITLE
Running test makes my image disappear 

### ISSUE THREAD

**Issue by just1witness** [freeCodeCamp/testable-projects-fcc#522] opened 2018-08-13 20:29 UTC
Tribute page

Clicking "run tests" makes one of my images disappear. I only press "run test", there is no change in the code, and nothing else is selected.

* Browser Name, Version: Firefox 61.0.2 (I know chrome works better, but chrome breaks my pc, so it's not an option for me)
* Operating System: Win 10 64bit
* Mobile, Desktop, or Tablet: Desktop Intel(R) Core(TM0 I5-7400 @3.00ghz

 https://codepen.io/Just1witness/pen/pZBogE
 
 

Before
![image](https://user-images.githubusercontent.com/29514150/44056268-bf87ef02-9f15-11e8-838a-9837316871b3.png)
After
![image](https://user-images.githubusercontent.com/29514150/44056281-c80671c6-9f15-11e8-88ab-4f632cb64841.png)

(On a side note... :'( Why do I _have_ to center my images? That's not how I want it to look :'(

**Comment by just1witness** [comment] 2018-08-13 20:30
On a side note, why do I have to center my images, It doesn't work with my desired layout :'(

**Comment by just1witness** [comment] 2018-08-14 02:19
It's worth noting. I was able to finish this project. I just thought an FYI could be helpful. I don't need nor expect a response. :)

**Comment by tbushman** [comment] 2018-08-14 18:35
Could be similar to #419 where the test removed and then (seemingly unsuccessfully) put back _inline_ styles. Thanks.

**Comment by tchaffee** [comment] 2018-08-14 22:19
@just1witness I can't reproduce this problem at the CodePen link you provided. Since you said you were able to pass the tests I am closing this. I would normally be more concerned, but I think we know what this is already and we have a PR ready to fix it.

**Closed by tchaffee** 2018-08-14 22:19 UTC
