### ISSUE TITLE
Product Landing Page navbar test passes when there is no navbar

### ISSUE THREAD

**Issue by sfiquet** [freeCodeCamp/testable-projects-fcc#280] opened 2018-01-24 13:09 UTC
#### Issue Description

- Fork the CodePen test pen
- select test suite for Product Landing Page
- run tests - Content 1 fails
- add a header with id to pass the test (see below)
- run tests - Content 1 passes but also Layout 1 "1. The navbar should always be at the top of the viewport."

#### Browser Information

* Browser Name, Version: Google Chrome Canari, Version 66.0.3329.1 (Official Build) canary (64-bit)
* Operating System: OS X
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

```
 <header id="header">My product</header>

 
 
```

#### Screenshot

![screen shot 2018-01-24 at 13 05 23](https://user-images.githubusercontent.com/4646869/35333656-6cb4385a-0107-11e8-83bd-7ad0740132a7.png)

**Comment by tchaffee** [comment] 2018-07-09 17:07
@sfiquet Thank you for reporting this. The test passes because the element with the id="header" does in fact stay at the top of the viewport using just the code you supplied. This is working as designed.

We could make the test clearer? What do you think about the following wording instead?

```
The header element and any of its children such as the navbar should always be at the top of the viewport.
```

**Comment by tchaffee** [comment] 2018-07-13 19:22
> So there are really two requirements:

> there should be a navbar

Yes, this test already exists in the "Content" section of tests.

![selection_149](https://user-images.githubusercontent.com/148813/42710004-bbe1bb14-86b8-11e8-9863-f8de533a9299.png)


I suppose we *could* change the layout test to first check for the presence of a navbar element... I'm kind of on the fence about that. I tend to defer to checking for the existence of an element in one place only unless it will cause the tests to crash.

The reason I try to put the tests in one place only is because once in a while our tests will have a bug in them. And if I repeat the code somewhere else it just increases the chance that I fix a bug in one place but forget about the other place. There is no "right" way to do this, just pros and cons.

Given that the user story about the nav bar existing is already there, do you think the it's ok and we can close this?

**Comment by sfiquet** [comment] 2018-07-13 21:00
I see what you mean. I guess it doesn't really matter. Feel free to close the issue.

Concerning the CDN link, I just found that it has already been reported twice and there's already a PR for it.

**Comment by tchaffee** [comment] 2018-07-13 21:12
@sfiquet Thanks for following through with the issue. Much appreciated.

**Closed by tchaffee** 2018-07-13 21:12 UTC
