### ISSUE TITLE
Product Landing Page false positive for nav-bar on top

### ISSUE THREAD

**Issue by floxSE** [freeCodeCamp/testable-projects-fcc#970] opened 2019-09-19 10:55 UTC
All tests are passing, but at least 1 of them shouldn't.

OS: macOS 10.14.6
Broswer: Chrome

Landing Page Project:
Layout Test 1:
the test for the nav-bar to remain on top of the page passes, even though i hadn't yet implemented it and it didn't stay there with my code.

here's the lnk to my code, please disregard content and design :)
https://codepen.io/floxSE/pen/bGbQboW

**Comment by tbushman** [comment] 2019-10-08 21:48
Although the project is progressed, we've had other similar issues opened. Layout test 1 of the Product Landing Page project passes for projects without `nav` content.

**Comment by tbushman** [comment] 2019-12-14 18:58
Duplicate of #529

**Comment by moT01** [comment] 2020-09-18 23:54
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉

**Closed by moT01** 2020-09-18 23:54 UTC
Labels: duplicate, help wanted, valid bug - reproduced
