### ISSUE TITLE
Personal Portfolio nav-link not working

### ISSUE THREAD

**Issue by natalie-coder** [freeCodeCamp/testable-projects-fcc#1131] opened 2020-05-15 16:49 UTC
Personal Portfolio

“User Story #7: The navbar should contain at least one link that I can click on to navigate to different sections of the page.”

my code fails the test for test 7 and I can't see what is wrong

#### Browser Information
- Browser Name, Version: Chrome
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Apple Mac

#### Your Code / Link to Your Pen

https://codepen.io/Natalieh23/pen/vYNzXbd

<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>

<nav id="navbar">
  <ul>
    <li><a href="#welcome-section">Welcome</a>
    </li>
    <li><a href="#projects">Projects</a></li>
    <li><a href="#contact">Contact</a></li>
    <li><a href="#about">About</a></li>
  </ul>
</nav>
<section id="welcome-section">
  <h1>Welcome</h1>
  <p>text</p>
</section>
<section id="projects">Projects
  <div class="project-tile">
    <a href="https://codepen.io/Natalieh23/pen/VwvQPZz">Link to project here</a>
    text
  </div>
</section>
<section id="contact">Contact details
  text</section>
<section id="about">About
  text</section>

**Comment by Sky020** [comment] 2020-05-15 18:45
Hello there,

In general, I recommend you open this kind of issue on the [forum](https://www.freecodecamp.org/forum), as the issue is not with the source code or the test suite, but your code.

In your case, the tests cannot _navigate_ to the sections of your page, because your page is smaller than the height of the window.

I am closing this issue. Thank you.

**Closed by Sky020** 2020-05-15 18:45 UTC
