### ISSUE TITLE
Navbar issue

### ISSUE THREAD

**Issue by rico042002** [freeCodeCamp/testable-projects-fcc#1133] opened 2020-05-17 01:02 UTC
#### Issue Description

The Navbar sticks to the top and goes to section when clicked, but I fail the two tests based on the navbar. 

#### Browser Information

- Browser Name, Version: Chrome
- Operating System: Windows
- Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen
https://codepen.io/rico042002/pen/ZgJKKy

```



```

**Comment by Sky020** [comment] 2020-05-17 10:33
Hello there,

In general, I recommend you open an issue like this on the [forum](https://www.freecodecamp.org/forum). The reason for this is the issue is not to do with the source code/test suite, but your code.

Specifically, you have not satisfied the requirements. Here is an example:
>Each .nav-link element should have an href attribute

```
<li class="nav-link"><a href="#topPage">Top of page</a></li>
```
The `.nav-link` element does not have an `href` attribute.

I am closing this issue. Thank you.

**Closed by Sky020** 2020-05-17 10:33 UTC
