### ISSUE TITLE
Video Issues in FCC - Product Landing Page test

### ISSUE THREAD

**Issue by nare0317** [freeCodeCamp/testable-projects-fcc#441] opened 2018-07-11 09:50 UTC
#### Issue Description

I have a constant error with the below item _(#content 6.  I can watch an embedded product video with id="video")_although I embedded product video in my code with id="video". 
Don't know what's wrong.  

#### Browser Information

* Browser Name, Version: Chrome, 67.0.3396.99
* Operating System: macOS High Sierra
* Mobile, Desktop, or Tablet: Laptop(MacBook Air)

#### Your Code / Link to Your Pen

```
 <section class="menus" id="menus"> 
  <iframe id="video" width="600" height="315" src="https://www.youtube.com/embed/mYObH4uH9u4?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen>    </iframe>
</section>
 
 
```

#### Screenshot

![2018-07-11 6 51 19](https://user-images.githubusercontent.com/40656125/42564402-9c537716-853b-11e8-8e53-a11d380c3064.png)

**Comment by tbushman** [comment] 2018-07-13 21:52
@nare0317 Thank you for bringing this to our attention. I hope it's fixed for you...

**Comment by nare0317** [comment] 2018-07-16 04:55
Thanks for trying, but unfortunately I still have same issue :(

**Comment by tbushman** [comment] 2018-07-16 07:14
@nare0317 OK, a new PR is pending that may fix it. :/ 

Will you please try removing the whitespace in ...`allowfullscreen>    </iframe>` between the opening and closing tags so we can make sure the whitespace isn't being checked for attributes.

**Comment by tbushman** [comment] 2018-07-24 02:07
@nare0317 This should have been fixed in #456 so if when you reload your project the issue is still there, let us know.

**Closed** 2018-08-09 03:38 UTC

**Comment by SpecialAgentOne** [comment] 2018-11-09 09:55
Hello, so i tried to fix this issue in my project by removing spaces between iframe elements and do other things, but still have same error, that script couldn`t found the video tag.

And if i copy code from the example, i still recieve an error.

Link to my project:
[https://codepen.io/SpecialAgentOne/pen/OogyXy]

Error message is below:
`#video should be an <iframe> or <video> element 
AssertionError: #video should be an <iframe> or <video> element 
    at e.assert (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:221:79)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:306545)
    at c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:31608)
    at o.f.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:31544)
    at m.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:37114)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:37976
    at s (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36426)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36495
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:35901)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36313`

**Comment by ValeraS** [comment] 2018-11-09 11:16
@SpecialAgentOne you have another element with `id="video"`, delete it for pass the test.

**Comment by SpecialAgentOne** [comment] 2018-11-09 14:07
@ValeraS Thank you! You are the hero of my day!
