### ISSUE TITLE
[Pomodoro clock] "before all" / "after all" hooks

### ISSUE THREAD

**Issue by ktminks** [freeCodeCamp/testable-projects-fcc#201] opened 2017-09-01 15:05 UTC
#### Issue Description

Pomodoro clock project: open blank template provided to fork from and run tests.
All tests fail but don't provide testing information, instead just giving 2 errors: "before all" hook and "after all" hook: TypeError: Cannot read property 'click' of null.
Tests run successfully on fork of provided example project until example's HTML and/or JS is deleted.

#### Browser Information

* Browser Name, Version: Version 60.0.3112.112 (Official Build) (64-bit)
* Operating System: Chrome OS
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

``` 
Blank template to fork from: https://codepen.io/freeCodeCamp/pen/MJjpwO
Provided example project: https://codepen.io/freeCodeCamp/full/XpKrrW
My pen: https://codepen.io/ktminks/pen/oeJZEo
 
 
```

#### Screenshot

![screenshot 2017-09-01 at 11 04 11 am - display 1](https://user-images.githubusercontent.com/19628386/29975715-637fd5f6-8f05-11e7-9b0c-c86542438d6f.png)

**Comment by tbushman** [comment] 2017-09-01 16:29
@ktminks Thanks for reporting this. @tchaffee the error is occurring where chai is imported.  
`Uncaught ReferenceError: __webpack_require__ is not defined`  
I can look into this in a couple of hours, but I think other suites are affected.

**Comment by tchaffee** [comment] 2017-09-01 17:31
@tbushman I'm not sure this has to do with importing chai, even though that's where the error is. There seems to be something wrong with the bundle.js. When I rebuild the bundle.js locally everything works fine. I think there is just something wrong with the bundle. I'm going to push a PR that uses the rebuilt bundle.

**Comment by tchaffee** [comment] 2017-09-01 18:31
@ktminks There was a problem with the bundle we load from the CDN. It might take an hour or two to update, but if you want to continue working now, you can go to your CodePen settings, then the javascript tab, and find the following:

```
https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js
```

And change that to:

```
https://rawgit.com/freeCodeCamp/testable-projects-fcc/master/build/bundle.js
```

If you don't want to change that setting, you can just wait a couple of hours and it should start working again. Please re-open the issue if you still have problems. Thanks again for reporting this.

**Comment by tbushman** [comment] 2017-09-01 18:41
@tchaffee Looks like two of the tests are not passing in pomodoro. I think it may be an issue with the mutation observer so I need to look into that later today.

**Comment by tchaffee** [comment] 2017-09-01 22:44
@tbushman Is that just for you locally? All of the Pomodoro tests pass for me on the offical sample Codepen.

**Comment by tbushman** [comment] 2017-09-02 02:44
It's been passing all tests now. I'm not sure what was up with that. :/

**Comment by ktminks** [comment] 2017-09-02 17:57
Hmm. I'm still getting the same issue. Blank template gives hook errors with both gitcdn and rawgit links. Tests run fine on official sample project but give hook errors if I delete its JS code.
Wasn't sure if it had something to do with ChromeOS, so I'm running on Win10 using the latest Chrome now.

**Comment by tchaffee** [comment] 2017-09-02 18:07
@ktminks There is one part of the JS that is essential:

```
const project_name = 'pomodoro-clock';
localStorage.setItem('example_project', 'Pomodoro Clock');
```

Can you make sure you have at least those two lines and let us know if you are still getting the error?

**Comment by tchaffee** [comment] 2017-09-02 18:09
@ktminks I was able to reproduce the problem when forking the blank template. We will look into that.

**Comment by ktminks** [comment] 2017-09-02 18:21
Alright. I left those two lines on the example project and still get hook errors.
![untitled](https://user-images.githubusercontent.com/19628386/29997760-c8afde64-8fe9-11e7-9196-64960f2f7bbd.png)

**Comment by tchaffee** [comment] 2017-09-02 18:45
@ktminks I have a fix ready, I'm just waiting for @tbushman to review it and merge it. We will let you know. 

In the meantime, I found another problem with our Pomodoro Clock tests. They don't play well with the alerts you are using if the user tries to click to the session time or break time below zero. You'll want to remove those alerts for now. I will see if we can fix the tests to work well with the alerts, but that might take some time.

**Comment by tchaffee** [comment] 2017-09-02 19:52
@ktminks You can temporarily use this link in your javascript settings, but you'll have to remove the alerts first, and you definitely have to change your javascript settings back to using the official CDN bundle.js once we get the fix merged.

```
https://rawgit.com/tchaffee/testable-projects-fcc/fix/pomodoro-clock-click/build/bundle.js
```

**Comment by tchaffee** [comment] 2017-09-02 22:37
For some reason gitcdn.link takes a very long time... you can use rawgit instead. They do the same thing and either one is fine to use permanently in your project. Rawgit already has the updates:

https://cdn.rawgit.com/freeCodeCamp/testable-projects-fcc/master/build/bundle.js

**Comment by tchaffee** [comment] 2017-09-04 14:54
@ktminks is this working for you now?

**Comment by ktminks** [comment] 2017-09-04 17:35
Yes. Hook errors are resolved ... Tests run on the blank template and on my project. Thank you for addressing this so quickly.
I've been trying to alter a previously built project to pass the tests, but 10 refuse to pass despite appropriate id's and the app behaving as described in the test. Errors are unhelpful, so I'm not sure if this is due to my design decisions or test errors.
Error: timeout of 5000ms exceeded, ensure the done() callback is being called in this test
TypeError: cannot read property '1' of null
Sorry if this is a separate issue (or not an issue).

**Comment by tchaffee** [comment] 2017-09-04 17:51
@ktminks I am going to close this issue and please open another issue for the other project(s) you are having problems with. Thanks for reporting these errors so we can get the beta site working for everyone!

**Closed by tchaffee** 2017-09-04 17:51 UTC
