### ISSUE TITLE
Problem with portfolio navbar at the top

### ISSUE THREAD

**Issue by Rem0ld** [freeCodeCamp/testable-projects-fcc#1176] opened 2020-06-26 02:55 UTC
#### Issue Description

When I run the test, it says the navbar should stay at the top of the viewport when scrolling which is happening.
I tried with `!important` after `top` and `position` but test still fails.
![Screenshot_2020-06-25 Portfolio Pierre Lovergne Front-End Developer](https://user-images.githubusercontent.com/60188728/85815600-d94c6180-b736-11ea-822e-d92cb25c5e06.png)

#### Browser Information

- Browser Name, Version: Chrome, 83
- Operating System: Mac OS Mojave
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

[https://portf-pierre.glitch.me/](url)
```
.navbar {
  display: flex;
  flex-direction: column;
  position: fixed;
  top: 0;
  width: 100%;
  height: auto;
  max-height: 200px;
  z-index: 5;
  background-color: rgba(56, 80, 114, 0.658);
}
.navbar ul {
  width: 100%;
}
.navbar a {
  color: #d4d3d3;
  display: block;
  padding: 2%;
}
.navbar__link {
  display: block;
  width: 100%;
  height: auto;
  margin: 0;
  padding: 0;
  text-align: center;
  color: #d4d3d3;
  font-size: 2em;
  cursor: pointer;
}


```

**Comment by Sky020** [comment] 2020-06-26 10:13
Hello there,

The issue is that you have given the class `.navbar` to the `ul` element, and not the `nav` element. This causes your `nav` element to have 0 height, and not inherit the `position: fixed` property, which is failing the tests.

I am closing this issue. I hope this helps

**Closed by Sky020** 2020-06-26 10:13 UTC
