### ISSUE TITLE
Front End Libraries Projects - Build a Pomodoro Clock User Story #8:

### ISSUE THREAD

**Issue by Kames105** [freeCodeCamp/testable-projects-fcc#1192] opened 2020-07-17 04:42 UTC
#### Browser Information

clearly have id labelled yet not passing 
- Browser Name, Version: chrome
- Operating System:windows codePen
- Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen https://codepen.io/james_1055/pen/yLeRqxr?editors=0010

```



```

#### [Screenshot](url)

]([url]([url]([url](url
<img width="902" alt="Bug " src="https://user-images.githubusercontent.com/58121311/87749210-63ba4980-c83b-11ea-8135-edf693f9f262.png">
))))

**Comment by Sky020** [comment] 2020-07-17 11:27
Hello there,

In general, I recommend you open an issue like this on the [forum](https://forum.freecodecamp.org/), as the issue is not with the test suite, but your code, and it is much easier to help over there.

I am not sure whether you have changed something in your pen, but it is no longer working:
![image](https://user-images.githubusercontent.com/51722130/87780545-da008100-c826-11ea-8d45-40d524418038.png)

The issue above arises, because the `timer-label` is not updating as the `session-length` is changed.

I am closing this issue. Thank you.

**Closed by Sky020** 2020-07-17 11:27 UTC
