### ISSUE TITLE
User Story #14 in Technical Documentation Page project

### ISSUE THREAD

**Issue by Feline17** [freeCodeCamp/testable-projects-fcc#1144] opened 2020-05-31 00:11 UTC
#### Issue Description
User Story #14 does not test correctly.

User Story #14: On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user.

Code that doesn't pass the test but should:
`#navbar {
  position: fixed;
  top: 0px;
  left: 10px;
}`

 Code that passes the test but shouldn't: 
`#navbar {
  position: fixed;
  top: 0px;
  left: -100px;
}`

#### Browser Information

- Browser Name, Version: Google Chrome Version 83.0.4103.61
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
[https://codepen.io/Feline17/pen/zYvgqEE](url)
```

#### Screenshot

![image](https://user-images.githubusercontent.com/24922168/83341398-14a06f80-a2f4-11ea-9df2-14bb9ae8fff0.png)

**Comment by Sky020** [comment] 2020-05-31 11:09
Hello there,

In general, I recommend you open an issue like this on the [forum](https://www.freecodecamp.org/forum), as the issue is not with the source code, but your code.

In your particular case: As you have pointed out, the user story is
>...the element with id="navbar" should be shown on the left side of the screen

The picture below shows where your element with `id="navbar"` is. It is clearly not on the left side of the screen. In my opinion, neither `left: 10px;` nor `left: -100px;` should pass the tests.
The example project shows what is _generally_ expected.

![image](https://user-images.githubusercontent.com/51722130/83350853-eabc6c80-a336-11ea-952d-0f9ae5f2a435.png)

I am closing this issue. I hope this helps.

**Closed by Sky020** 2020-05-31 11:09 UTC
