### ISSUE TITLE
javaScript Calculator test suite bug

### ISSUE THREAD

**Issue by mcrombie** [freeCodeCamp/testable-projects-fcc#933] opened 2019-07-24 19:22 UTC
#### Issue Description

There seems to be a bug in the test suite for user story #13. Also, that user story does not include the note at the end to exclude negative sign on the main documentation page, only in the test suite.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://user-images.githubusercontent.com/17343123/61821929-419b1080-ae0d-11e9-8a6c-b44d7fc5ce0d.png)

![image](https://user-images.githubusercontent.com/17343123/61821962-54ade080-ae0d-11e9-863e-d3b9155f9780.png)

**Comment by Steffan153** [comment] 2019-07-24 19:58
> There seems to be a bug in the test suite for user story #13.

Haha github thinks you're talking about pull request #13 :laughing:

**Comment by ksalzke** [comment] 2019-07-25 21:04
I’m seeing this too. I would like to have a go at fixing this bug. Am I okay to go ahead and start working on this or do I need to wait until it has been confirmed? (This would be my first contribution, so I don’t want to mess up the process!)

**Comment by Steffan153** [comment] 2019-07-25 21:39
That's no problem! Just make sure to test it locally, then edit it on here and create a PR.
Make sure to read the contributing guidelines too :smile:

**Comment by ksalzke** [comment] 2019-07-26 03:48
Great - of course I’ll do all that, thanks @Steffan153!

Agreed that 5 - 5 = 0! But that said:

The user story on the FCC site is “User Story #13: If 2 or more operators are entered consecutively, the operation performed should be the last operator  i.e. * is ignored and 5 - 5 = 0.

The user story in the calculator-tests.js file is different and actually says “If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (_excluding the negative (-) sign)_ ie * is not ignored and 5 * -5 = 25.

To me both options make sense and in fact a quick test shows that Apple’s calculator app does the first while Google’s does the second.

Is it possible the test should be edited so that both treatments are acceptable?

**Comment by Steffan153** [comment] 2019-07-26 13:12
> both treatments are acceptable?

You can try that.
In chai (used by this), there are a few ways to do this, try one of these:
https://www.chaijs.com/api/bdd/#method_oneof
https://www.chaijs.com/api/bdd/#method_satisfy

**Comment by ksalzke** [comment] 2019-07-27 10:00
Hmmm. I forked and cloned the repository and ran the tests locally and they all passed; so I did some further investigation.

It looks like the Javascript Calculator project has already been updated to pass the test (which was changed with pull request #910 ) with this commit: https://github.com/freeCodeCamp/testable-projects-fcc/commit/3a947dbea861a510dd052fbea2657f7370500cc2

However the CodePen doesn't reflect these changes yet. (Once I copied the above code into CodePen all the tests passed again.)

Discussion of the issue #908 suggests that 5 * -5 = -25 is the intended treatment.

So, I think that:

1. The CodePen needs to be updated - @no-stack-dub-sack or @QuincyLarson, based on the contribution guidelines I think that you need to make this change?
2. The challenge page needs to be updated to reflect the changed tests. I have created a pull request for this here: https://github.com/freeCodeCamp/freeCodeCamp/pull/36523

**Comment by tbushman** [comment] 2019-07-28 04:42
@ksalzke Thank you! Thanks for your time. @scissorsneedfoodtoo I'm sorry I forgot to mention that the Javascript Calculator code was updated recently and so the Codepen needs the code from `/src/projects/javascript-calculator/index.jsx` in this repo. Thank you!

**Comment by Steffan153** [comment] 2019-07-28 12:16
Apparently, the change broke a bunch of calculators though... including mine.

**Comment by scissorsneedfoodtoo** [comment] 2019-08-06 02:28
@tbushman, no need to apologize! Thank you for letting me know. I'm sorry I missed this earlier. I'll update the code on codepen right away.

**Comment by scissorsneedfoodtoo** [comment] 2019-08-06 02:35
Just updated the Pen now. Here's the link: https://codepen.io/freeCodeCamp/pen/wgGVVX

**Comment by scissorsneedfoodtoo** [comment] 2019-09-19 08:52
Closed via https://github.com/freeCodeCamp/freeCodeCamp/pull/36523.

**Closed by scissorsneedfoodtoo** 2019-09-19 08:52 UTC
Labels: bug
