### ISSUE TITLE
The <img> element should responsively resize, relative to the width of its parent element, without exceeding its original size.

### ISSUE THREAD

**Issue by alaga-droid** [freeCodeCamp/testable-projects-fcc#1118] opened 2020-05-03 18:52 UTC
Hello, I am receiving the error above when I run my test for my Tribute Page project @FreeCodeCamp.
If anyone sees the issue, please help. Thank you.

My CodePen: https://codepen.io/algala-droid/full/ExVwazK.

**Comment by Sky020** [comment] 2020-05-03 19:03
Hello there,

In general, I suggest you open an _issue_ like this on the [forum](https://www.freecodecamp.org/forum).

Reason being, the issue is not with the source code, but your code. Specifically, your HTML has many syntax errors. I suggest you use the built-in analyse tool in CodePen to help you find them.

I am closing this issue. Thank you.

**Closed by Sky020** 2020-05-03 19:03 UTC
