### ISSUE TITLE
Product Landing Page test suite

### ISSUE THREAD

**Issue by otamm** [freeCodeCamp/testable-projects-fcc#820] opened 2019-03-08 04:23 UTC
The exact same code for the layout tests (especifally the flexbox and media query ones) pass when they are inside <style></style> tags inside the <head> component but not when the CSS is being fetched in a file.
Here's my repo with the file: https://github.com/otamm/-fcc-test-suite-template/blob/master/landing-page.html

I'm sending you the relevant files (changed landing-page.css to landing-page-css, changed them both to .txt files):

[landing-page.txt](https://github.com/freeCodeCamp/testable-projects-fcc/files/2944377/landing-page.txt)
[landing-page-css.txt](https://github.com/freeCodeCamp/testable-projects-fcc/files/2944378/landing-page-css.txt)

**Comment by dloret** [comment] 2019-03-13 06:38
I suppose I face the same issue. My HTML file is linked to a css file that updates the display correctly, so the setup is ok. When I run the test, I got 14 out 16: the tests for "display: flex" and media queries fails, despite the following css file:
`header {
  display: flex;
}

header > img {
  width: 20%;
}

main {
  display: grid;
}

@media only screen and (min-device-width: 668px) {
  header > img {
    width: 40%;
  }
}`

**Comment by dloret** [comment] 2019-03-13 06:42
Duplicate of #749

**Comment by dloret** [comment] 2019-03-13 06:47
Duplicate of #813

**Comment by tbushman** [comment] 2019-04-08 15:48
@otamm @dloret Is this working for you now? If not, please try running your project through live-server.

**Comment by dloret** [comment] 2019-04-09 06:05
Hi, it worked once deployed in the AWS bucket. I'll see how to proceed for
the next projects. Thanks & kind regards,  Donatien

Le lun. 8 avr. 2019 à 17:48, Tracey Bushman <notifications@github.com> a
écrit :

**Closed** 2019-12-14 18:59 UTC
