### ISSUE TITLE
Product Landing Page No Nav Bar yet Passes

### ISSUE THREAD

**Issue by Shadowslip71** [freeCodeCamp/testable-projects-fcc#704] opened 2018-11-18 13:30 UTC
#### Issue Description

Hi

I know this has been reported but it is still very confusing as header and nav html tags are very different.

The test "1. The navbar should always be at the top of the viewport." in the product landing page passes even though there is no nav bar.

#### Browser Information

* Browser Name, Version: Firefox 63.0 
* Operating System: Ubuntu
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js">
</script>

<header id="header">
  the header
</header>
```

**Comment by tbushman** [comment] 2019-12-14 19:00
Duplicate of #529

**Comment by moT01** [comment] 2020-09-18 23:51
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉

**Closed by moT01** 2020-09-18 23:51 UTC
Labels: duplicate
