### ISSUE TITLE
personal portfolio error

### ISSUE THREAD

**Issue by jhonny-99** [freeCodeCamp/testable-projects-fcc#1130] opened 2020-05-14 17:19 UTC
#### Issue Description

Hello
I cannot finish the portfolio project due to some error regarding task number 8.
The link is doing all the required but is still show me that is wrong
#### Browser Information

- Browser Name, Version: Chrome
- Operating System:WIndows 10
- Mobile, Desktop, or Tablet:Desktop

#### Your Code / Link to Your Pen
<a 
        id="profile-link" 
        href="https://github.com/freecodecamp"
        target=”_blank” 
        ><i class="fab fa-github"></i> Github</a>

![profile-link](https://user-images.githubusercontent.com/65356306/81964924-fb26d480-961f-11ea-810e-5a8e5650af24.PNG)
![pennerror](https://user-images.githubusercontent.com/65356306/81964926-fc580180-961f-11ea-97a4-f2261728caf1.PNG)

**Comment by jhonny-99** [comment] 2020-05-14 17:22
This is the code that I tray to add and is not working
<li><a 
        id="profile-link" 
        href="https://github.com/freecodecamp"
        target=”_blank” 
        ><i class="fab fa-github"></i> Github</a>
</li>

**Comment by Sky020** [comment] 2020-05-14 17:27
Hello there,

In general, I recommend you open an issue like this on the [forum](https://www.freecodecamp.org/forum). This is because the issue is not related to the source code, nor the test suite, but your code.

In this specific case, you can see the detailed issue the error is giving you. The quotations used around the `_blank` value of the `target` attribute are not the standard `"` quotation marks.

I am closing this issue. Thank you.

**Closed by Sky020** 2020-05-14 17:27 UTC
