### ISSUE TITLE
img issue

### ISSUE THREAD

**Issue by Thanoja28** [freeCodeCamp/testable-projects-fcc#1135] opened 2020-05-19 14:53 UTC
<img width="960" alt="2020-05-18 (1)" src="https://user-images.githubusercontent.com/49320255/82341695-a94bc900-99e8-11ea-8dbd-2fee66760ce6.png">

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Thanoja28** [comment] 2020-05-19 14:54
could anyone clear this issue please???

**Comment by Sky020** [comment] 2020-05-19 15:35
Hello @Thanoja28 ,

In general, I recommend you open an issue like this on the [forum](https://www.freecodecamp.org/forum). Reason being, the issue is not with the source code, nor the test suite, but is with your code.

When you open a topic on the forum, be sure to include a link to your project, otherwise we cannot help much.

I am closing this issue. Thank you.

**Closed by Sky020** 2020-05-19 15:35 UTC

**Comment by Thanoja28** [comment] 2020-05-19 17:07
Thank you for your reply let me do that 


Sent from Yahoo Mail for iPhone


On Tuesday, May 19, 2020, 4:36 pm, Shaun Hamilton <notifications@github.com> wrote:




Closed #1135.
