### ISSUE TITLE
FCC: Personal Portfolio -

### ISSUE THREAD

**Issue by rickvian** [freeCodeCamp/testable-projects-fcc#709] opened 2018-11-19 02:25 UTC
Responsive Web Design Projects - Build a Personal Portfolio Webpage
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage

#### Issue Description

I'm currently learning this one 
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage
and i open the code pen

https://codepen.io/freeCodeCamp/full/zNBOYG
when i run test, there is an error for EXAMPLE codepen above

This is the error:
The height of the welcome section should be equal to the height of the viewport.

i really want to know the problem, and how i can solve it, thanks

#### Browser Information

* Browser Name, Version:Chrome Version 70.0.3538.102 (Official Build) (64-bit)
* Operating System: Mac OS Mojave 10.14.1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
https://codepen.io/freeCodeCamp/full/zNBOYG



 
```

#### Screenshot

![screen shot 2018-11-19 at 09 25 38](https://user-images.githubusercontent.com/8034141/48682917-24a6a180-ebdd-11e8-9308-be6992f0d5c7.jpg)

**Comment by ValeraS** [comment] 2018-11-19 06:58
duplicate of #658

**Closed** 2018-11-20 04:11 UTC
