### ISSUE TITLE
in my personal portofolio for free codecamp i used media query but the system did not recognize 

### ISSUE THREAD

**Issue by Abroa** [freeCodeCamp/testable-projects-fcc#1155] opened 2020-06-04 16:16 UTC
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment] 2020-06-04 17:07
Hello there,

In general, I recommend you open an issue like this on the [forum](https://www.freecodecamp.org/forum).

As the content of this issue contains no information, it is invalid. I suggest you open a topic on the forum, and, if the issue is deemed to be related to the source code, and not your code, reopen an issue here with the relative details.

I am closing this issue. Thank you.

**Closed by Sky020** 2020-06-04 17:07 UTC
