### ISSUE TITLE
Hey, though the img tag is responsive I am not able to clear the user story#9

### ISSUE THREAD

**Issue by ZiyaSayed** [freeCodeCamp/testable-projects-fcc#1151] opened 2020-06-03 12:54 UTC
here is the link: https://codepen.io/Ziya_Sayed/pen/wvMvyBX

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment] 2020-06-03 14:28
Hello there,

In general, I recommend opening an issue like this on the [forum](https://www.freecodecamp.org/forum), as the issue is not with the source code or test suite, but your code.

Specifically, I suggest you make use of the very specific error messages:
>Try using the "max-width" style property : expected 'none' to not equal 'none'

Keep applying the responsive web design principles, and you will pass the tests.

I am closing this issue. Thank you.

**Closed by Sky020** 2020-06-03 14:28 UTC
