### ISSUE TITLE
Build a Personal Portfolio Webpage Error

### ISSUE THREAD

**Issue by Acole5** [freeCodeCamp/testable-projects-fcc#927] opened 2019-07-10 22:29 UTC
#### Issue Description

I have completed all the requirement in the users story and I still have some errors when I run the test:
5. The projects section should contain at least one link to a project.
8. My portfolio should have a link with an id of "profile-link", which opens my GitHub or FCC profile in a new tab.
3. The navbar should always be at the top of the viewport.

#### Browser Information

* Browser Name, Version: 
Google Chrome is up to date
Version 75.0.3770.100 (Official Build) (64-bit)

Firefox Quantum
Version 68.0 (64-bit)

* Operating System: 
Windows 10 Home

* Mobile, Desktop, or Tablet: 
Laptop:
Lenovo Ideapad 320

#### Your Code / Link to Your Pen

```
 https://codepen.io/Acole424/pen/MMLPgo

![fccerrors](https://user-images.githubusercontent.com/4987757/61009282-d2ff8280-a337-11e9-9ccc-3290d3d6d5ca.png)
 
 
```

**Comment by lasjorg** [comment] 2019-07-18 01:42
1. For `#5` I think it is because of the Codepen embeds are inside an iframe. You will have to add links to the projects outside the iframes.

2. For `#8` the id `#profile-link` has to be on an `<a>` element and you have it on a `<section>` element.

3. For `#3` you can add `position: fixed;` to the `#navbar` element.

For this kind of help, it is better to post to the [fCC forum](https://www.freecodecamp.org/forum/).

**Comment by RandellDawson** [comment] 2019-07-18 02:27
Closing this as a non-issue, because the problem is the user's code.

@Acole5 In the future, please use the forum first and only open an issue if the forum users determine there actually is a bug in the tests.  Thank you.

**Closed by RandellDawson** 2019-07-18 02:27 UTC
