### ISSUE TITLE
5. When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.'

### ISSUE THREAD

**Issue by Mnabawy** [freeCodeCamp/testable-projects-fcc#509] opened 2018-08-06 15:08 UTC
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment] 2018-08-09 04:17
@Mnabawy We need more information to investigate the issue. Please share a link to your project or code.

**Comment by tchaffee** [comment] 2018-08-14 22:28
@Mnabawy I am closing this because we don't have enough info to reproduce the problem. If you can give us a link to your CodePen we will be happy to reopen the issue.

**Closed by tchaffee** 2018-08-14 22:28 UTC
