### ISSUE TITLE
Javascript Calculator decimal point tests fail when display does not show trailing zero

### ISSUE THREAD

**Issue by aaronRhodebeck** [freeCodeCamp/testable-projects-fcc#253] opened 2017-10-27 20:57 UTC
#### Issue Description

In test # 11 for the Javascript Calculator --*When the decimal element is clicked, a . should append to the currently displayed value; two. .s should not be accepted".
The test requires the display to read "5.0" when pressing `5`, `.`, `.`, `0`.  Anyone displaying a number instead of a string will fail the test due to removal of the insignificant 0.
I recommend changing the test so that the last number is not a zero and this will allow multiple ways to display the number.  

#### Your Code / Link to Your Pen
I have built this project in React and not sure the best way to share it, so I will link to the [GitHub repo](https://github.com/aaronRhodebeck/FCCJavascriptCalculator/tree/fcc-tests) and try to paste some relevant code below.

Here is the test code
```
 clickButtonsById([_5, _dec, _dec, _0]);
 FCC_Global.assert.strictEqual(document.getElementById("display").innerHTML, "5.0", 'An input of 5 . . 0 should display 5.0 '); 
```
Here is an example of how I am displaying the number (inputs are put into a formula which is also displayed)
```
const total = calculateTotalFrom(formula); // returns number instead of string
<p id="display">{total}</p> // does not show unnecessary trailing zeros i.e. "5.0"

```

I would be more than happy to change the test and submit a PR if you would like.

**Comment by tbushman** [comment] 2017-10-28 05:49
@aaronRhodebeck When you want to type '5.01', does an intermediary '5.0' appear in your calculator window before typing the trailing '1'? The trailing '0' when typing '5.0' is expected behavior for a calculator.

**Comment by tchaffee** [comment] 2017-11-23 15:04
I'm closing this because I agree with @tbushman that this is expected behavior for a calculator. Typing "5.0" should display both the dot and the zero. That's what all calculators do. If we are wrong about this, or you would like to discuss more, please feel free to re-open the issue.

**Closed by tchaffee** 2017-11-23 15:04 UTC
